name: pf_subsetter
channels:
  - conda-forge
  - defaults
dependencies:
  - basemap
  - gdal
  - geos
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.7.6
  - pip:
    - pyqt5-sip
    - pyqtwebengine
    - parflowio